apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: app-ns
  labels:
    name: app
    version: v1
  #annotations:
    #volume.beta.kubernetes.io/storage-provisioner: "dobs.csi.digitalocean.com"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
