---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    version: v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  namespace: apps
  labels:
    name: fortune
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: fortune
      version: v2
  template:
    metadata:
      name: fortune-pod
      labels:
        name: fortune
        version: v2
    spec:
      containers:
      - name: fortune-container
        image: njmingz/course-example-fortune:v0.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - name: fortune-port
          containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  namespace: apps
  labels:
    name: fortune
    version: v2
spec:
  type: LoadBalancer
  selector:
    name: fortune
    version: v2
  ports:
  - name: http
    port: 80
    targetPort: fortune-port
