apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: apps
  labels:
    name: fortune
    version: v2
spec:
  containers:
  - name: fortune-container
    image: njmingz/course-example-fortune:v0.0.2
    imagePullPolicy: IfNotPresent
    env:
    - name: APP_PORT
      value: "3000"
    ports:
    - name: http
      containerPort: 3000