---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  namespace: apps
  labels:
    name: fortune
    version: v2
spec:
  type: LoadBalancer
  selector:
    name: fortune
    version: v2
  ports:
  - name: http
    port: 80
    targetPort: fortune-port
